language: node_js

sudo: false

node_js:
    - "0.12"

notifications:
      slack: tpi:6tDHJnEix8HsEU4fpca4fgBB

before_script:

    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

    - npm link .
    - tibet build
    - cd ..
    - tibet clone travis
    - cd travis
    - tibet init --link
    - npm install -g karma-cli
    - npm install --save-dev karma
    - npm install --save-dev karma-chrome-launcher
    - npm install --save-dev karma-tibet
    - tibet config karma.boot.profile="main#contributor"
    - tibet config karma.script=":test"
    - tibet config karma.timeout=120000

script:
    - karma start --debug
    #./node_modules/karma/bin/karma start karma.conf.js --single-run

      # Karma vs. npm test
#script: node_modules/karma/bin/karma start test/karma.conf.js --single-run

# Google Chrome
#
# https://github.com/travis-ci/travis-ci/issues/272#issuecomment-14402117
# http://stackoverflow.com/questions/19255976/how-to-make-travis-execute-angular-tests-on-chrome-please-set-env-variable-chr

