language: node_js

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js:
    - "0.12"

notifications:
    slack: tpi:6tDHJnEix8HsEU4fpca4fgBB
    email: false

before_script:

    - npm link .
    - tibet build
    - cd ..
    - tibet clone travis
    - cd travis
    - tibet init --link
    - npm install -g karma-cli
    - npm install --save-dev karma
    - npm install --save-dev karma-chrome-launcher
    - npm install --save-dev karma-tibet
    - tibet config karma.boot.profile="main#contributor"
    - tibet config karma.script=":test --context='all'"

    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - karma start --debug
